server:
  port: 8093

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ecommerce:
  rabbitmq:
    exchange: ecommerce.topic.exchange
    queues:
      admin-events-queue: ecommerce.admin.events.queue
    routing-keys:
      order-created: order.created
      payment-completed: payment.completed
